import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'


//font configurations
const inter = Inter({ subsets: ["latin"] });
const spaceGrotesk=Space_Grotesk({
  subsets:['latin'],
  weight:['300','400','500','600','700']
})

//metadata obj
export const metadata: Metadata = {
  title: "Scrapezon",
  description: "Generated by next app",
};


//rootlayot comp that wraps whole app

export default function RootLayout({children}: {children: React.ReactNode;}) 
{
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="max-w-10xl mx-auto" >
        < Navbar />
        {children}
      </main>
      </body>

    </html>
  );
}
